spring:
 datasource:
  url: jdbc:mysql://localhost:3306/prime_generator
  username: root
  password: root
  
 jpa:
  generate-ddl: true
  show-sql: true
  hibernate.ddl-auto: update
  
server:
 port: 8085